### ISSUE TITLE
Register plugin with Cordova

### ISSUE THREAD

**Issue by flomio** [flomio/flomio_cordova_plugin#1]
Also, register the plugin with on http:/cordova.plugins.io as:

com.flomio.sdk

change: 

```
id="com.flomio.proximityid"
version="0.1.0">
<name>Flomio Proximity ID</name>
```

to:

```
id="com.flomio.sdk"
version="0.1.0">
<name>Flomio SDK</name>
```

**Comment by grundyoso** [comment]
this was added to npm which now seems to be managing cordova plugins: 

https://www.npmjs.com/package/cordova-plugin-flomio
