### ISSUE TITLE
Investigate how to automatically bundle the latest Flomio SDK with the plugin

### ISSUE THREAD

**Issue by stuart-xyz** [flomio/flomio_cordova_plugin#13]
When a Meteor / Cordova developer uses the Flomio Cordova plugin, and they try to build their app for mobile, errors are generated since the SDK static library is not automatically linked to the Xcode project. An automated process must be developed to improve the developer experience

**Comment by fschaeffler** [comment]
any updates on that task?

**Comment by scottire** [comment]
Automatic bundling has been added to v2.2
