### ISSUE TITLE
Where do I get the Flomio SDK?

### ISSUE THREAD

**Issue by cjaentsch** [flomio/flomio_cordova_plugin#15]
The only thing I found was at https://github.com/flomio/flomio_ios... but this source does not correspond to the description here! I have bought a FloJack reader...

**Comment by grundyoso** [comment]
The Basic Flomio SDK can be downloaded from Dropbox here: 

https://www.dropbox.com/s/y5qloadwievtjp4/FlomioSDK.zip?dl=0

it will only work with readers purchased from flomio.com as the device ids are validated against our license server.
