### ISSUE TITLE
Add Android support for Flomio SDK 

### ISSUE THREAD

**Issue by grundyoso** [flomio/flomio_cordova_plugin#16]
First pass should be to prove out the basic integration with the Flomio SDK to show the Teleport app functioning the same as on iOS. 

Second pass will be to implement all the APIs the the Flomio SDK should support.

**Comment by JohnMcLear** [comment]
Wondering if we have an ETA for this?

**Comment by grundyoso** [comment]
We need it for a customer deployment on July 1st, 2016 so I suspect we will have it before then... @darienalvarez has a version he hasn't committed but was waiting on @bpolania to publish the Android SDK first in order to make sure the API didn't change before committing.

**Comment by grundyoso** [comment]
The latest SDK2.0 supports Android now and can be downloaded from here: 

https://www.dropbox.com/s/y5qloadwievtjp4/FlomioSDK.zip?dl=1

Follow the readme instructions that have now been updated to 2.0 to verify proper operation.
