### ISSUE TITLE
addConnectedDevicesListener returns an object instead of an array

### ISSUE THREAD

**Issue by tylervz** [flomio/flomio_cordova_plugin#28]
When I inspected the callback of `addConnectedDevicesListener` using Safari , I discovered that the result was an object instead of an array.

![screen shot 2017-08-18 at 2 08 19 pm](https://user-images.githubusercontent.com/8753239/29578799-283b857a-8736-11e7-96b4-5086e774c603.png)

I would like to have it return an array, like the README states. I am using the `master` branch of this plugin.

**Comment by scottire** [comment]
Ok, apologies for error in documentation. Why do you want it to be an Array if you don't mind me asking?

**Comment by tylervz** [comment]
If an array was being returned I would be able to tell whether an NFC reader just connected or whether one disconnected, based on the size of the array. Right now I'm getting the same result when the reader connects and when it disconnects, so I cannot notify the user "An NFC reader just connected" and "No NFC readers are connected".

**Comment by scottire** [comment]
` let communicationStatus = updatedDevices["Communication Status"]`
Will tell you the status of the connect device. 
0 means disconnected
1 means connected but not polling for tags
2 means connected and polling for tags

**Comment by tylervz** [comment]
Are you sure that's right? I'm getting 0 when the reader connects and I'm getting 2 when I turn off my phone's bluetooth.
