### ISSUE TITLE
Document and streamline the plugin install and app building 

### ISSUE THREAD

**Issue by grundyoso** [flomio/flomio_cordova_plugin#7]
It's time consuming and complex to setup a Meteor or Ionic app with this Flomio SDK plugin. Need to document simplest way to do it so developers can pickup and go quickly.

**Comment by stuart-xyz** [comment]
The latest commits go a large way towards addressing this: [here](https://github.com/flomio/flomio_cordova_plugin/commit/41baf650804b9bc14148c2bdcbbbc81fec884ff4) and [here](https://github.com/flomio/flomio_cordova_plugin/commit/855832b86df9d32f964f8eff864fa5b18f059a01)

**Comment by grundyoso** [comment]
this has been verified by a few customers so closing it,.
